### ISSUE TITLE
Capture from canvas: Strength of reference?

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-fromelement#17]
Is the reference from the capturing track to the Canvas a strong reference or a weak reference?

If it's a strong reference, and all other references to the canvas are lost, we can assume that the picture will become a still picture.

If it's a weak reference, and the canvas is garbage collected, we would have to assume (and the track should say) that the track ends.

Which do we want?

**Comment by martinthomson** [comment]
Javascript doesn't have the concept of a weak reference, not really.  I know that browser implementations often have to resort to tricks like that, but in this case I don't see any reason to have the reference be weak.  If the only reference to the canvas is via the captured stream, that's perfectly OK to my mind, expected even.
