### ISSUE TITLE
Blocking on pause

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-fromelement#2]
Firefox implements an extension to what is described in the current draft for paused media elements.

When the media element is paused, the captured stream enters a "blocking" state, and progress on the output streams halts.  There is no similar concept in the real-time MediaStream, so if a similar concept was introduced, then there would need to be patches to MediaStream(Track) to support that.

**Comment by padenot** [comment]
We (Mozilla) are thinking of removing blocking because it's not a useful concept. The spec as it is is probably what we'll end up doing.

**Comment by martinthomson** [comment]
I will ask, but @padenot is right, we are ripping out the code.  I'm going to close this.
