### ISSUE TITLE
Specify what happens when frameRate is negative

### ISSUE THREAD

**Issue by foolip** [w3c/mediacapture-fromelement#26]
Blink throws a `NotSupportedError` exception:
https://chromium.googlesource.com/chromium/src/+/2bd49bae7f8c7d3cfaa02bed77c56cc474c19bfb/third_party/WebKit/Source/modules/mediacapturefromelement/HTMLCanvasElementCapture.cpp#29

**Comment by martinthomson** [comment]
Closed by #33
