### ISSUE TITLE
Should it be possible to call canvas.captureStream() before canvas.getContext()?

### ISSUE THREAD

**Issue by foolip** [w3c/mediacapture-fromelement#31]
``` HTML
<!DOCTYPE html>
<canvas></canvas><video></video>
<script>
var canvas = document.querySelector('canvas');
var ms = canvas.captureStream();
</script>
```

Here, Firefox throws a `NS_ERROR_NOT_INITIALIZED` exception, while Chrome does not. The spec doesn't say anything about this.

**Comment by uysalere** [comment]
Should we throw an InvalidAccessError?

**Comment by foolip** [comment]
If it really shouldn't be possible to call `canvas.captureStream()` before `canvas.getContext()`, then I'd say `InvalidStateError`, which is used in somewhat analogous situations in https://dom.spec.whatwg.org/#dom-eventtarget-dispatchevent and https://mediasession.spec.whatwg.org/#dom-htmlmediaelement-session

In Blink, is there any complexity added by allowing the calls in any order? If there isn't, then it'd be interesting to learn why Firefox has this restriction.

**Comment by uysalere** [comment]
In Blink, there isn't an issue about the order of the calls. There won't be any frames captured until the context is defined.

**Comment by Pehrsons** [comment]
In Firefox we used to rely on there being a context available at all times. It looks like we cleared that requirement with the last refactor though, so throwing won't be needed. I have filed [a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1257440) to remove this.

**Comment by foolip** [comment]
Excellent! AFAICT no spec change is required, feel free to close if that's the case.

**Comment by martinthomson** [comment]
Closing based on the last comment.  @uysalere, you should take note of this when you write up the proposed solution to #29.

**Comment by eslamelhadedy** [comment]
i have the same problem any solution
