### ISSUE TITLE
What happens to the audio being rendered to a Media Element when it gets captureStream()ed

### ISSUE THREAD

**Issue by yell0wd0g** [w3c/mediacapture-fromelement#34]
During [Chrome implementation](https://codereview.chromium.org/1781043002/) of [captureStream()](http://w3c.github.io/mediacapture-fromelement/#html-media-element-media-capture-extensions) for <audio> elements or <video> elements with audio active, @dalecurtis brought up the question of what is the model for accessing the Media Element audio data, i.e. what happens if the media tag is playing back a certain audio track, after captureStream() successfully returns a MediaStream with (at least) and audio track:
- the audio being played back is routed exclusively to the Track, hence the Media Element playback "stops"
- the audio being played back is "copied" to the MediaStream Track.

I understand this might be a question for the Media Element itself, @foolip?

**Comment by martinthomson** [comment]
The audio should be copied, just as video is.  If that isn't obvious, a pull request or text suggestion might help me identify where any confusion might arise.

**Comment by dalecurtis** [comment]
Unlike video, you can't hide the audio, so by virtue of requiring a copy a developer can never suppress local playout of media. Where as they can play the captured stream locally if they so desire if the default is redirection.

**Comment by martinthomson** [comment]
I'm not sure that's true.  Maybe this isn't clear in the spec, but we permit the capture of a muted `HTMLMediaElement`.  That is, `muted` only applies to the connection between the element and the speakers, it doesn't affect whether a given track is considered to be available for capture.

**Comment by dalecurtis** [comment]
Gotcha, that would resolve my concerns then. So developers can set element.muted = true and capture will continue w/ normal audio. As a followup question is volume supposed to be applied to the captured stream?

**Comment by yell0wd0g** [comment]
Filed #35 for the question of the audio volume.

**Comment by foolip** [comment]
Unless overruled by some other spec (which I'd call "monkey patching") what HTML says still applies. I noticed a small problem there, but the bits quoted in https://github.com/whatwg/html/issues/860 are what makes media elements noisy :)

If there are good use cases for muting a media element at the same time that `captureStream()` begins, then a small problem is the difficulty (impossibility?) or setting `muted` at precisely the correct time. If there's any use case for gapless handoff of audio, it would probably need additional APIs. That's feels pretty far off given the current state of things, though :)

**Comment by Pehrsons** [comment]
Chiming in a bit late here, but note that the `MediaElementAudioSourceNode` in WebAudio does re-route the audio completely. I.e., the media element appears muted, and volume is applied to the audio going through the node.

**Comment by jan-ivar** [comment]
Conclusion appears to be that audio continues to play thanks to the HTML spec, and existing ways to avoid that through WebAudio or element mute seem sufficient.
