### ISSUE TITLE
CD publication of specification

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-fromelement#47]
At the Lisbon TPAC meeting, we will raise the question of whether this spec is ready for publication as CD. Please add to this issue references to the issues that you think have to be resolved before CD publication.

Once all these are resolved, and we think review is adequate, we will ask for CD publication.

Harald, for the chairs.

**Comment by jan-ivar** [comment]
Closing as this is instead tracked by the [Candidate Recommendation](https://github.com/w3c/mediacapture-fromelement/milestone/1) milestone.
