### ISSUE TITLE
WG CR review for mediacapture-fromelement

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-fromelement#50]
This issue serves to track internal WG review (in the WGs making up the mediacapture TF) of the mediacapture-fromelement document for CR publication.
If you have reviewed the document, please add a “thumbs up” reaction to the issue.
If you find issues that you think need addressing before CR publication, please file the issue in Github and mention it in the comments.

The review lasts until Thursday, October 12, 2016. At that time, the chairs will decide whether or not the review result warrants asking the wider community to review the document for CR; if we do ask the wider community, a similar issue wil be filed for tracking that review.

**Comment by fluffy** [comment]
A question for the chairs, given the number of fairly substantial open issues on this, do the chairs think it read for CR?

**Comment by fluffy** [comment]
I think that many of issues need to be resolved before this is ready for CR

**Comment by jan-ivar** [comment]
Closing as this is instead tracked by the [Candidate Recommendation](https://github.com/w3c/mediacapture-fromelement/milestone/1) milestone.
