### ISSUE TITLE
captureStream() should return a promise

### ISSUE THREAD

**Issue by guidou** [w3c/mediacapture-fromelement#66]
captureStream() returning a fully configured MediaStream introduces restrictions for the implementation since the stream and its tracks have to be configured synchronously.
It would be more flexible if it returned a promise, like getUserMedia() which resolves the promise with the fully configrued stream and allows asynchronous creation.

**Comment by yell0wd0g** [comment]
Same as https://github.com/w3c/mediacapture-fromelement/issues/58?

**Comment by guidou** [comment]
Indeed. Closing as it's a duplicate.
