### ISSUE TITLE
Clarify 'origin' concept

### ISSUE THREAD

**Issue by stefhak** [w3c/mediacapture-fromelement#73]
From https://lists.w3.org/Archives/Public/public-media-capture/2018Feb/0005.html:
"From Element has its own developed privacy considerations section, particularly focused on origin separation. Is it expected that handling origin separation is to be handled by implementors or is there best practices or implementation guidelines that will be provided?  If the latter, is Feature Policy an applicable solution here?"

This issue was (by mistake) originally opened in [mediacapture-screen-share repo](https://github.com/w3c/mediacapture-screen-share/issues/53), but belongs here. Please see the discussion in that Issue.

**Comment by martinthomson** [comment]
No, that issue was correct.  The issue on screen sharing was to highlight the complete absence of information.  This spec might be a little light on detail, but it does consider this point.  (The mention of this spec was to highlight the difference.)

**Comment by aboba** [comment]
@martinthomson  Can we close this issue?

**Comment by martinthomson** [comment]
I think so.  If we get a clearer problem statement, maybe that will be actionable.
