### ISSUE TITLE
Clarify if requestFrame is intended to be defined as a method of CanvasCaptureMediaStream or MediaStreamTrack

### ISSUE THREAD

**Issue by guest271314** [w3c/mediacapture-fromelement#76]
The specification appears to state that `requestFrame()` is a method of `CanvasCaptureMediaStreamTrack`. However, at Mozilla Firefox `requestFrame` is a method of `CanvasCaptureMediaStream` not `MediaStreamTrack`. 

See 

- https://bugzilla.mozilla.org/show_bug.cgi?id=1446864

- https://github.com/mdn/browser-compat-data/pull/2372

**Comment by guest271314** [comment]
Related https://github.com/web-platform-tests/wpt/issues/10088. The issue persists at Firefox 65 and Chromium 72

**Comment by alvestrand** [comment]
The initial revision of mediastream-fromelement was written in terms of capturing a stream.
Eventually it was realized that what could be captured from a canvas only made sense as a single MediaStreamTrack, and the specification was rewritten in the form of CanvasCaptureMediaStreamTrack.

The implementations are artifacts of these older specifications, and should be corrected.
Chrome's IDL conforms to the spec: https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/mediacapturefromelement/canvas_capture_media_stream_track.idl?type=cs&g=0

**Comment by alvestrand** [comment]
[I recommend that this bug be labelled "question" and closed, but don't have edit rights on this repo]

**Comment by Pehrsons** [comment]
The right Firefox bug to follow is https://bugzilla.mozilla.org/show_bug.cgi?id=1231131
